# Generated by Django 3.0.8 on 2020-08-27 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sm_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentaltestfieldtype',
            name='final_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentaltestfieldtype',
            name='initial_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentaltestfield',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mental_test_fields', to='sm_tests.MentalTest'),
        ),
    ]
