# Generated by Django 3.0.8 on 2020-08-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_tests', '0002_auto_20200827_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentaltestfieldtype',
            name='final_label',
            field=models.CharField(default='Nada En Absoluto', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentaltestfieldtype',
            name='initial_label',
            field=models.CharField(default='Extremadamente', max_length=255),
            preserve_default=False,
        ),
    ]
