# Generated by Django 3.0.8 on 2020-10-04 06:39
from django.conf import settings
from django.db import migrations
from django.contrib.auth.models import Group


def bootstrap_permissions(apps, schema_editor):
    #read_only
    group, created = Group.objects.get_or_create(name='hr_admin')   
    group, created = Group.objects.get_or_create(name='standard_user') 


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sm_tests', '0004_auto_20201004_0542'),

    ]

    operations = [
        migrations.RunPython(bootstrap_permissions),
    ]
