# Generated by Django 3.0.8 on 2020-11-29 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sm_tests', '10000_permissions_bootstrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalTestDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagnosis_test', to='sm_tests.MentalTest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagnosis_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
