# Generated by Django 3.0.8 on 2020-12-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm_tests', '10001_mentaltestdiagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentaltest',
            name='alias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
