#
# Self deploy development pod for podman
# Don't forget to change the path in the volumes section
# (c) SotolitoLabs
#
# Iván Chavero <ichavero@chavero.com.mx>

apiVersion: v1
kind: Pod
metadata:
  name: django-env
spec:
  containers:
  - name: django-nginx
    image: quay.io/sotolitolabs/django-rest-nginx:latest
    ports:
    - containerPort: 80
      hostPort: 8081
    volumeMounts:
    - name: nginx
      mountPath: /usr/share/nginx/html
  - name: django-postgres
    image: quay.io/sotolitolabs/django-postgresql:latest
    ports:
    - containerPort: 5432
    env:
    - name: DJANGO_DB
      value: test_db 
    - name: DJANGO_DB_USER 
      value: test_user 
    - name: DJANGO_PASSWORD
      value: prueba123
    - name: POSTGRES_PASSWORD
      value: prueba123 
    volumeMounts:
    - name: postgres
      mountPath: /var/lib/postgresql/data
  - name: django-rest
    image: quay.io/sotolitolabs/django-rest:latest
    command: ["/code/sm/manage.py", "runserver"]
    ports:
    - containerPort: 8000
      hostPort: 8000
    volumeMounts:
    - name: code
      mountPath: /code
  volumes:
  - name: nginx
    hostPath:
      path: /home/<changeme>/sotolitoLabs/sm/src/sm/sm_tests/static
      type: Directory
  - name: postgres
    hostPath:
      path: /home/<changeme>/tmp/salud_mental/django-postgres/
      type: Directory
  - name: code
    hostPath:
      path: /home/<changeme>/sotolitoLabs/sm/src
      type: Directory





